version: "{build}"

image: Visual Studio 2017

environment:
  matrix:
  - llvm: 3.7.1
  - llvm: 3.8.1
  - llvm: 3.9.1
  - llvm: 4.0.1
  - llvm: 5.0.0

configuration:
  - release
  - debug

clone_depth: 100
skip_tags: true
skip_commits:
  files:
    - .bintray.sh
    - .gitattributes
    - .gitignore
    - .gitmodules
    - .travis.yml
    - .travis_install.bash
    - .travis_script.bash
    - Dockerfile
    - LICENSE
    - Makefile
    - release.bash
    - '**/*.md'
    - '**/*.txt'

clone_folder: C:\projects\ponyc

build_script:
  - ps: |
      $package_commit = git rev-parse --short --verify "HEAD^{commit}"
      $package_version = (Get-Content "VERSION")
      $package_iteration = "$package_iteration${env:appveyor_build_number}.$package_commit"
      Update-AppveyorBuild -Version "ponyc-$package_version-$package_iteration"
  - cd C:\projects\ponyc
  - python -x waf configure
  - python -x waf build --config %configuration% --llvm %llvm%
  - ps: |
      $ponydir = "ponyc-${package_version}-win64"
      cd C:\projects\ponyc
      md "$ponydir"
      md "${ponydir}\ponyc"
      md "${ponydir}\ponyc\bin"
      $builddir = "C:\projects\ponyc\build\${env:configuration}-llvm-${env:llvm}"
      Write-Output "Build dir is ${builddir}"
      copy $builddir\ponyc.* "${ponydir}\ponyc\bin"
      copy $builddir\ponyrt.* "${ponydir}\ponyc\bin"
      copy $builddir\*.lib "${ponydir}\ponyc\bin"
      copy -recurse packages "${ponydir}\packages"
      copy -recurse ".docs" "${ponydir}\docs-support"
      7z a -tzip "C:\projects\ponyc\${ponydir}.zip" "${ponydir}"

test_script:
  - cd C:\projects\ponyc
  - python -x waf test --config %configuration% --llvm %llvm%
