version: "{build}"

image: Visual Studio 2015

environment:
  matrix:
  - llvm: 3.9.1
  - llvm: 3.8.1
  - llvm: 3.7.1

configuration:
  - release
  - debug

clone_depth: 100

clone_folder: C:\projects\ponyc

install:
  - ps: |
      $package_commit = git rev-parse --short --verify "HEAD^{commit}"
      $package_version = (Get-Content "VERSION")
      $package_iteration = "$package_iteration${env:appveyor_build_number}.$package_commit"
      Update-AppveyorBuild -Version "ponyc-${env:appveyor_repo_branch}-$package_version-$package_iteration"
  - cd C:\projects\ponyc
  - python -x waf configure
  - python -x waf build --config %configuration% --llvm %llvm%
  - ps: |
      $ponydir = "${env:appveyor_build_version}-win64"
      cd C:\projects\ponyc
      md "$ponydir"
      md "${ponydir}\ponyc"
      md "${ponydir}\ponyc\bin"
      $builddir = "C:\projects\ponyc\build\${env:configuration}-llvm-${env:llvm}"
      Write-Output "Build dir is ${builddir}"
      copy $builddir\ponyc.* "${ponydir}\ponyc\bin"
      copy $builddir\ponyrt.* "${ponydir}\ponyc\bin"
      copy $builddir\*.lib "${ponydir}\ponyc\bin"
      copy -recurse packages "${ponydir}\packages"
      7z a -tzip "C:\projects\ponyc\${ponydir}.zip" "${ponydir}"

build:
  none

test_script:
  - ps: |
      cd C:\projects\ponyc
      python -x waf test --config $env:configuration --llvm $env:llvm
