language: c

dist: trusty
sudo: required

services:
  - docker

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=yes
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="4.0.1"
        - LLVM_CONFIG="llvm-config-4.0"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="4.0.1"
        - LLVM_CONFIG="llvm-config-4.0"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="5.0.0"
        - LLVM_CONFIG="llvm-config-5.0"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="5.0.0"
        - LLVM_CONFIG="llvm-config-5.0"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6

    # i686
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=i686
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=-m32
        - CROSS_CXXFLAGS=-m32
        - CROSS_LDFLAGS=-m32
        - CROSS_BITS=32
        - CROSS_TRIPLE=i686-unknown-linux-gnu
        - CROSS_LINKER='gcc-6 -m32'
        - CROSS_CC=gcc-6
        - CROSS_CXX=g++-6
        - CROSS_TUNE=generic

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=i686
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=-m32
        - CROSS_CXXFLAGS=-m32
        - CROSS_LDFLAGS=-m32
        - CROSS_BITS=32
        - CROSS_TRIPLE=i686-unknown-linux-gnu
        - CROSS_LINKER='gcc-6 -m32'
        - CROSS_CC=gcc-6
        - CROSS_CXX=g++-6
        - CROSS_TUNE=generic

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=i686
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=-m32
        - CROSS_CXXFLAGS=-m32
        - CROSS_LDFLAGS=-m32
        - CROSS_BITS=32
        - CROSS_TRIPLE=i686-unknown-linux-gnu
        - CROSS_LINKER='gcc-6 -m32'
        - CROSS_CC=gcc-6
        - CROSS_CXX=g++-6
        - CROSS_TUNE=generic

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=i686
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=-m32
        - CROSS_CXXFLAGS=-m32
        - CROSS_LDFLAGS=-m32
        - CROSS_BITS=32
        - CROSS_TRIPLE=i686-unknown-linux-gnu
        - CROSS_LINKER='gcc-6 -m32'
        - CROSS_CC=gcc-6
        - CROSS_CXX=g++-6
        - CROSS_TUNE=generic

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=i686
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=-m32
        - CROSS_CXXFLAGS=-m32
        - CROSS_LDFLAGS=-m32
        - CROSS_BITS=32
        - CROSS_TRIPLE=i686-unknown-linux-gnu
        - CROSS_LINKER='gcc-6 -m32'
        - CROSS_CC=gcc-6
        - CROSS_CXX=g++-6
        - CROSS_TUNE=generic

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=i686
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=-m32
        - CROSS_CXXFLAGS=-m32
        - CROSS_LDFLAGS=-m32
        - CROSS_BITS=32
        - CROSS_TRIPLE=i686-unknown-linux-gnu
        - CROSS_LINKER='gcc-6 -m32'
        - CROSS_CC=gcc-6
        - CROSS_CXX=g++-6
        - CROSS_TUNE=generic

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=i686
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="4.0.1"
        - LLVM_CONFIG="llvm-config-4.0"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=-m32
        - CROSS_CXXFLAGS=-m32
        - CROSS_LDFLAGS=-m32
        - CROSS_BITS=32
        - CROSS_TRIPLE=i686-unknown-linux-gnu
        - CROSS_LINKER='gcc-6 -m32'
        - CROSS_CC=gcc-6
        - CROSS_CXX=g++-6
        - CROSS_TUNE=generic

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=i686
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="4.0.1"
        - LLVM_CONFIG="llvm-config-4.0"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=-m32
        - CROSS_CXXFLAGS=-m32
        - CROSS_LDFLAGS=-m32
        - CROSS_BITS=32
        - CROSS_TRIPLE=i686-unknown-linux-gnu
        - CROSS_LINKER='gcc-6 -m32'
        - CROSS_CC=gcc-6
        - CROSS_CXX=g++-6
        - CROSS_TUNE=generic

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=i686
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="5.0.0"
        - LLVM_CONFIG="llvm-config-5.0"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=-m32
        - CROSS_CXXFLAGS=-m32
        - CROSS_LDFLAGS=-m32
        - CROSS_BITS=32
        - CROSS_TRIPLE=i686-unknown-linux-gnu
        - CROSS_LINKER='gcc-6 -m32'
        - CROSS_CC=gcc-6
        - CROSS_CXX=g++-6
        - CROSS_TUNE=generic

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=i686
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="5.0.0"
        - LLVM_CONFIG="llvm-config-5.0"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=-m32
        - CROSS_CXXFLAGS=-m32
        - CROSS_LDFLAGS=-m32
        - CROSS_BITS=32
        - CROSS_TRIPLE=i686-unknown-linux-gnu
        - CROSS_LINKER='gcc-6 -m32'
        - CROSS_CC=gcc-6
        - CROSS_CXX=g++-6
        - CROSS_TUNE=generic

    # armv7-a
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=armv7-a
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=
        - CROSS_CXXFLAGS=
        - CROSS_LDFLAGS=
        - CROSS_BITS=32
        - CROSS_TRIPLE=arm-unknown-linux-gnueabihf
        - CROSS_LINKER=arm-linux-gnueabihf-gcc
        - CROSS_CC=arm-linux-gnueabihf-gcc
        - CROSS_CXX=arm-linux-gnueabihf-g++
        - QEMU_RUNNER='qemu-arm-static -L /usr/local/arm-linux-gnueabihf/libc'
        - CROSS_TUNE=generic-armv7-a

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=armv7-a
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=
        - CROSS_CXXFLAGS=
        - CROSS_LDFLAGS=
        - CROSS_BITS=32
        - CROSS_TRIPLE=arm-unknown-linux-gnueabihf
        - CROSS_LINKER=arm-linux-gnueabihf-gcc
        - CROSS_CC=arm-linux-gnueabihf-gcc
        - CROSS_CXX=arm-linux-gnueabihf-g++
        - QEMU_RUNNER='qemu-arm-static -L /usr/local/arm-linux-gnueabihf/libc'
        - CROSS_TUNE=generic-armv7-a

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=armv7-a
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=
        - CROSS_CXXFLAGS=
        - CROSS_LDFLAGS=
        - CROSS_BITS=32
        - CROSS_TRIPLE=arm-unknown-linux-gnueabihf
        - CROSS_LINKER=arm-linux-gnueabihf-gcc
        - CROSS_CC=arm-linux-gnueabihf-gcc
        - CROSS_CXX=arm-linux-gnueabihf-g++
        - QEMU_RUNNER='qemu-arm-static -L /usr/local/arm-linux-gnueabihf/libc'
        - CROSS_TUNE=generic-armv7-a

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=armv7-a
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=
        - CROSS_CXXFLAGS=
        - CROSS_LDFLAGS=
        - CROSS_BITS=32
        - CROSS_TRIPLE=arm-unknown-linux-gnueabihf
        - CROSS_LINKER=arm-linux-gnueabihf-gcc
        - CROSS_CC=arm-linux-gnueabihf-gcc
        - CROSS_CXX=arm-linux-gnueabihf-g++
        - QEMU_RUNNER='qemu-arm-static -L /usr/local/arm-linux-gnueabihf/libc'
        - CROSS_TUNE=generic-armv7-a

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=armv7-a
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=
        - CROSS_CXXFLAGS=
        - CROSS_LDFLAGS=
        - CROSS_BITS=32
        - CROSS_TRIPLE=arm-unknown-linux-gnueabihf
        - CROSS_LINKER=arm-linux-gnueabihf-gcc
        - CROSS_CC=arm-linux-gnueabihf-gcc
        - CROSS_CXX=arm-linux-gnueabihf-g++
        - QEMU_RUNNER='qemu-arm-static -L /usr/local/arm-linux-gnueabihf/libc'
        - CROSS_TUNE=generic-armv7-a

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=armv7-a
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=
        - CROSS_CXXFLAGS=
        - CROSS_LDFLAGS=
        - CROSS_BITS=32
        - CROSS_TRIPLE=arm-unknown-linux-gnueabihf
        - CROSS_LINKER=arm-linux-gnueabihf-gcc
        - CROSS_CC=arm-linux-gnueabihf-gcc
        - CROSS_CXX=arm-linux-gnueabihf-g++
        - QEMU_RUNNER='qemu-arm-static -L /usr/local/arm-linux-gnueabihf/libc'
        - CROSS_TUNE=generic-armv7-a

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=armv7-a
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="4.0.1"
        - LLVM_CONFIG="llvm-config-4.0"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=
        - CROSS_CXXFLAGS=
        - CROSS_LDFLAGS=
        - CROSS_BITS=32
        - CROSS_TRIPLE=arm-unknown-linux-gnueabihf
        - CROSS_LINKER=arm-linux-gnueabihf-gcc
        - CROSS_CC=arm-linux-gnueabihf-gcc
        - CROSS_CXX=arm-linux-gnueabihf-g++
        - QEMU_RUNNER='qemu-arm-static -L /usr/local/arm-linux-gnueabihf/libc'
        - CROSS_TUNE=generic-armv7-a

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=armv7-a
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="4.0.1"
        - LLVM_CONFIG="llvm-config-4.0"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=
        - CROSS_CXXFLAGS=
        - CROSS_LDFLAGS=
        - CROSS_BITS=32
        - CROSS_TRIPLE=arm-unknown-linux-gnueabihf
        - CROSS_LINKER=arm-linux-gnueabihf-gcc
        - CROSS_CC=arm-linux-gnueabihf-gcc
        - CROSS_CXX=arm-linux-gnueabihf-g++
        - QEMU_RUNNER='qemu-arm-static -L /usr/local/arm-linux-gnueabihf/libc'
        - CROSS_TUNE=generic-armv7-a

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=armv7-a
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="5.0.0"
        - LLVM_CONFIG="llvm-config-5.0"
        - config=debug
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=
        - CROSS_CXXFLAGS=
        - CROSS_LDFLAGS=
        - CROSS_BITS=32
        - CROSS_TRIPLE=arm-unknown-linux-gnueabihf
        - CROSS_LINKER=arm-linux-gnueabihf-gcc
        - CROSS_CC=arm-linux-gnueabihf-gcc
        - CROSS_CXX=arm-linux-gnueabihf-g++
        - QEMU_RUNNER='qemu-arm-static -L /usr/local/arm-linux-gnueabihf/libc'
        - CROSS_TUNE=generic-armv7-a

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CROSS_ARCH=armv7-a
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="5.0.0"
        - LLVM_CONFIG="llvm-config-5.0"
        - config=release
        - CC1=gcc
        - CXX1=g++
        - ICC1=gcc-6
        - ICXX1=g++-6
        - CROSS_CFLAGS=
        - CROSS_CXXFLAGS=
        - CROSS_LDFLAGS=
        - CROSS_BITS=32
        - CROSS_TRIPLE=arm-unknown-linux-gnueabihf
        - CROSS_LINKER=arm-linux-gnueabihf-gcc
        - CROSS_CC=arm-linux-gnueabihf-gcc
        - CROSS_CXX=arm-linux-gnueabihf-g++
        - QEMU_RUNNER='qemu-arm-static -L /usr/local/arm-linux-gnueabihf/libc'
        - CROSS_TUNE=generic-armv7-a

    - os: osx
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.7.1"
        - LLVM_CONFIG="llvm-config-3.7"
        - CC1=clang-3.7
        - CXX1=clang++-3.7

    - os: osx
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.8.1"
        - LLVM_CONFIG="llvm-config-3.8"
        - CC1=clang-3.8
        - CXX1=clang++-3.8

    - os: osx
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="3.9.1"
        - LLVM_CONFIG="llvm-config-3.9"
        - CC1=clang-3.9
        - CXX1=clang++-3.9

    - os: osx
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="4.0.1"
        - LLVM_CONFIG="llvm-config-4.0"
        - CC1=clang-4.0
        - CXX1=clang++-4.0

    - os: osx
      env:
        - CROSS_ARCH=
        - FAVORITE_CONFIG=no
        - LLVM_VERSION="5.0.0"
        - LLVM_CONFIG="llvm-config-5.0"
        - CC1=clang-5.0
        - CXX1=clang++-5.0

rvm:
  - 2.2.3

install:
  - bash .travis_install.bash

script:
  - bash .travis_script.bash
